# -*- coding: utf-8 -*-
# AUTO-GENERATED by license/gen_seal.py — DO NOT EDIT.
# SHA256 of critical function __code__ for self-integrity check.
SEAL = {'license.license_manager': 'ef28c0114c53001cb06d0c43a9249e51734266330bb6176383f8c3efb9059e31', 'license.license_guard': 'd48471979d16e34b23a7310d24a482d98d309372db02590f1a7a5843a4c2c508'}
